export const subjects = [
  { en: 'Physics', bn: 'পদার্থবিজ্ঞান' },
  { en: 'Chemistry', bn: 'রসায়ন' },
  { en: 'Biology', bn: 'জীববিজ্ঞান' },
  { en: 'Math', bn: 'গণিত' },
  { en: 'Higher Math', bn: 'উচ্চতর গণিত' },
  { en: 'ICT', bn: 'তথ্য ও যোগাযোগ প্রযুক্তি' },
  { en: 'Bangla', bn: 'বাংলা' },
  { en: 'English', bn: 'ইংরেজি' },
  { en: 'BGS', bn: 'বাংলাদেশ ও বিশ্বপরিচয়' },
  { en: 'History & Social Sci.', bn: 'ইতিহাস ও সমাজবিজ্ঞান' },
  { en: 'Geography & Env.', bn: 'ভূগোল ও পরিবেশ' },
  { en: 'Economics', bn: 'অর্থনীতি' },
  { en: 'Civics', bn: 'নাগরিক শিক্ষা' },
  { en: 'Accounting', bn: 'হিসাববিজ্ঞান' },
  { en: 'Business Principles', bn: 'ব্যবসায় নীতি' },
  { en: 'Finance & Banking', bn: 'অর্থ ও ব্যাংকিং' },
  { en: 'Islam & Moral Ed.', bn: 'ইসলাম ও নৈতিক শিক্ষা' },
  { en: 'Hindu Religion', bn: 'হিন্দু ধর্ম' },
  { en: 'Christian Religion', bn: 'ক্রিশ্চিয়ান ধর্ম' },
  { en: 'Buddhist Religion', bn: 'বৌদ্ধ ধর্ম' },
  { en: 'Agriculture', bn: 'কৃষি' },
  { en: 'Home Science', bn: 'গৃহ বিজ্ঞান' },
  { en: 'Phy. Education', bn: 'শারীরিক শিক্ষা' },
  { en: 'Work & Life Ed.', bn: 'কর্ম ও জীবনমুখী শিক্ষা' },
  { en: 'Arts & Crafts', bn: 'শিল্প ও হস্তশিল্প' },
  { en: 'Career Ed.', bn: 'ক্যারিয়ার শিক্ষা' }
];

export const tutorExamples = {
  'Physics': 'Explain Newton\'s Second Law of Motion',
  'Chemistry': 'Explain the process of balancing chemical equations',
  'Biology': 'Describe the process of mitosis and its importance',
  'Math': 'How do you solve a quadratic equation using the quadratic formula?',
  'Higher Math': 'How do you find the determinant of a 3x3 matrix?',
  'ICT': 'What is a computer network and what are its types?',
  'Bangla': 'পদ প্রকরণ কাকে বলে? উদাহরণ সহ ব্যাখ্যা করুন।',
  'English': 'Summarise the story of Nelson Mandela\'s fight for freedom',
  'BGS': 'What are the fundamental principles of the Constitution of Bangladesh?',
  'History & Social Sci.': 'What were the causes and effects of the Battle of Plassey?',
  'Geography & Env.': 'Describe the major river systems of Bangladesh',
  'Economics': 'Explain the law of demand and supply with examples',
  'Civics': 'What are the fundamental rights of citizens in Bangladesh?',
  'Accounting': 'What is double-entry bookkeeping? Explain with an example',
  'Business Principles': 'What are the different types of business organisations?',
  'Finance & Banking': 'How does mobile banking work in Bangladesh?',
  'Islam & Moral Ed.': 'What are the Five Pillars of Islam? Explain each briefly',
  'Hindu Religion': 'What are the core teachings of the Bhagavad Gita?',
  'Christian Religion': 'What are the Ten Commandments and their significance?',
  'Buddhist Religion': 'What are the Four Noble Truths in Buddhism?',
  'Agriculture': 'What are the major crops grown in Bangladesh?',
  'Home Science': 'What are the components of a balanced diet?',
  'Phy. Education': 'What are the benefits of regular physical exercise?',
  'Work & Life Ed.': 'What are the qualities of a good leader?',
  'Arts & Crafts': 'What are the traditional crafts of Bangladesh?',
  'Career Ed.': 'How do you plan for a successful career?',
};

export const tutorExamplesBn = {
  'Physics': 'নিউটনের দ্বিতীয় সূত্র ব্যাখ্যা করুন',
  'Chemistry': 'রাসায়নিক সমীকরণ ভারসাম্যের প্রক্রিয়া ব্যাখ্যা করুন',
  'Biology': 'মাইটোসিস প্রক্রিয়া ও এর গুরুত্ব বর্ণনা করুন',
  'Math': 'দ্বিঘাত সূত্র ব্যবহার করে কীভাবে দ্বিঘাত সমীকরণ সমাধান করবেন?',
  'Higher Math': 'কীভাবে ৩x৩ ম্যাট্রিক্সের ডিটারমিন্যান্ট বের করবেন?',
  'ICT': 'কম্পিউটার নেটওয়ার্ক কী এবং এর প্রকারভেদগুলো কী কী?',
  'Bangla': 'পদ প্রকরণ কাকে বলে? উদাহরণ সহ ব্যাখ্যা করুন।',
  'English': 'নেলসন ম্যান্ডেলার স্বাধীনতা সংগ্রামের গল্প সংক্ষেপে বলুন',
  'BGS': 'বাংলাদেশ সংবিধানের মৌলিক নীতিগুলো কী কী?',
  'History & Social Sci.': 'পলাশীর যুদ্ধের কারণ ও ফলাফল কী ছিল?',
  'Geography & Env.': 'বাংলাদেশের প্রধান নদী ব্যবস্থা বর্ণনা করুন',
  'Economics': 'চাহিদা ও যোগানের নিয়ম উদাহরণ সহ ব্যাখ্যা করুন',
  'Civics': 'বাংলাদেশে নাগরিকদের মৌলিক অধিকারগুলো কী কী?',
  'Accounting': 'দ্বৈত নথি পদ্ধতি কী? একটি উদাহরণ সহ ব্যাখ্যা করুন',
  'Business Principles': 'ব্যবসায় সংগঠনের বিভিন্ন প্রকার কী কী?',
  'Finance & Banking': 'বাংলাদেশে কীভাবে মোবাইল ব্যাংকিং কাজ করে?',
  'Islam & Moral Ed.': 'ইসলামের পঞ্চস্তম্ভ কী কী? প্রতিটি সংক্ষেপে ব্যাখ্যা করুন',
  'Hindu Religion': 'ভগবদ গীতার মূল শিক্ষাগুলো কী কী?',
  'Christian Religion': 'দশটি আদেশ কী এবং এর গুরুত্ব কী?',
  'Buddhist Religion': 'বৌদ্ধধর্মের চারটি মহৎ সত্য কী কী?',
  'Agriculture': 'বাংলাদেশের প্রধান ফসলগুলো কী কী?',
  'Home Science': 'সুষম খাদ্যের উপাদানগুলো কী কী?',
  'Phy. Education': 'নিয়মিত শারীরিক ব্যায়ামের সুবিধাগুলো কী কী?',
  'Work & Life Ed.': 'একজন ভালো নেতার গুণাবলী কী কী?',
  'Arts & Crafts': 'বাংলাদেশের ঐতিহ্যবাহী কারুশিল্পগুলো কী কী?',
  'Career Ed.': 'কীভাবে একটি সফল ক্যারিয়ারের পরিকল্পনা করবেন?',
};

export const questionExamples = {
  'Physics': 'Work, Power and Energy',
  'Chemistry': 'Chemical Reactions and Equations',
  'Biology': 'Cell Division and Genetics',
  'Math': 'Quadratic Equations',
  'Higher Math': 'Matrices and Determinants',
  'ICT': 'Programming Basics with Python',
  'Bangla': 'পদ প্রকরণ ও বাক্য',
  'English': 'Nelson Mandela: A Long Walk to Freedom',
  'BGS': 'Bangladesh Economy and Development',
  'History & Social Sci.': 'British Colonial Rule in Bengal',
  'Geography & Env.': 'Physical Geography of Bangladesh',
  'Economics': 'Basic Concepts of Economics',
  'Civics': 'Citizenship and Human Rights',
  'Accounting': 'Introduction to Accounting',
  'Business Principles': 'Business Environment and Organization',
  'Finance & Banking': 'Banking and Financial System of Bangladesh',
  'Islam & Moral Ed.': 'Islamic Beliefs and Modern Life',
  'Hindu Religion': 'Hindu Philosophy and Scriptures',
  'Christian Religion': 'Christian Life and Service',
  'Buddhist Religion': 'Buddhist Philosophy and Meditation',
  'Agriculture': 'Agriculture in Bangladesh',
  'Home Science': 'Nutrition and Meal Planning',
  'Phy. Education': 'Physical Fitness and Disease Prevention',
  'Work & Life Ed.': 'Career Planning and Financial Literacy',
  'Arts & Crafts': 'Bangladeshi Art Heritage and Design',
  'Career Ed.': 'Career Planning and Financial Literacy',
};

export const questionExamplesBn = {
  'Physics': 'কাজ, ক্ষমতা ও শক্তি',
  'Chemistry': 'রাসায়নিক বিক্রিয়া ও সমীকরণ',
  'Biology': 'কোষ বিভাজন ও জিনতত্ত্ব',
  'Math': 'দ্বিঘাত সমীকরণ',
  'Higher Math': 'ম্যাট্রিক্স ও ডিটারমিন্যান্ট',
  'ICT': 'পাইথন দিয়ে প্রোগ্রামিং',
  'Bangla': 'পদ প্রকরণ ও বাক্য',
  'English': 'নেলসন ম্যান্ডেলা',
  'BGS': 'বাংলাদেশের অর্থনীতি ও উন্নয়ন',
  'History & Social Sci.': 'বাংলায় ব্রিটিশ শাসন',
  'Geography & Env.': 'বাংলাদেশের ভৌগোলিক পরিচিতি',
  'Economics': 'অর্থনীতির মৌলিক ধারণা',
  'Civics': 'নাগরিকত্ব ও মানবাধিকার',
  'Accounting': 'হিসাববিজ্ঞানের পরিচিতি',
  'Business Principles': 'ব্যবসায় পরিবেশ ও সংগঠন',
  'Finance & Banking': 'ব্যাংকিং ও আর্থিক ব্যবস্থা',
  'Islam & Moral Ed.': 'ইসলামী বিশ্বাস ও আধুনিক জীবন',
  'Hindu Religion': 'হিন্দু দর্শন ও ধর্মগ্রন্থ',
  'Christian Religion': 'খ্রীষ্টিয় জীবন ও সেবা',
  'Buddhist Religion': 'বৌদ্ধ দর্শন ও ধ্যান',
  'Agriculture': 'বাংলাদেশে কৃষি',
  'Home Science': 'পুষ্টি ও খাদ্য পরিকল্পনা',
  'Phy. Education': 'শারীরিক সুস্থতা ও রোগ প্রতিরোধ',
  'Work & Life Ed.': 'ক্যারিয়ার পরিকল্পনা ও আর্থিক সাক্ষরতা',
  'Arts & Crafts': 'বাংলাদেশের শিল্প ঐতিহ্য ও নকশা',
  'Career Ed.': 'ক্যারিয়ার পরিকল্পনা ও আর্থিক সাক্ষরতা',
};

export const subjectToRAG = {
  'Physics': 'physics', 'Chemistry': 'chemistry', 'Biology': 'biology',
  'Math': 'math', 'Higher Math': 'higher-math', 'ICT': 'ict',
  'Bangla': 'bangla', 'English': 'english',
  'BGS': 'bgs', 'History & Social Sci.': 'history', 'Geography & Env.': 'geography',
  'Economics': 'economics', 'Civics': 'civics',
  'Accounting': 'accounting', 'Business Principles': 'business-principles',
  'Finance & Banking': 'finance-banking',
  'Islam & Moral Ed.': 'religion', 'Hindu Religion': 'hindu-religion',
  'Christian Religion': 'christian-religion', 'Buddhist Religion': 'buddhist-religion',
  'Agriculture': 'agriculture', 'Home Science': 'home-science',
  'Phy. Education': 'physical-education', 'Work & Life Ed.': 'work-life',
  'Arts & Crafts': 'arts-crafts', 'Career Ed.': 'career-education',
};
